server_port: 8080

database_address: '127.0.0.1'
database_port: 5432
database_name: 'nom'
database_username: ''
database_password: ''

refiner_data_store_directory: ''
pillars_off_chain_data_directory: ''