name: zt_server

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.3
  postgresql2: ^1.0.2
  settings_yaml: ^3.4.0
  hex: ^0.2.0
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: master